name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  security:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

          - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: |
        cd app
        npm install
        npm test
