name: SLSA Provenance

on:
  workflow_call: # this makes it callable from other workflows
    inputs:
      image:
        required: true
        type: string
      digest:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

permissions:
  id-token: write # needed for SLSA
  contents: read
  packages: write

jobs:
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_container_slsa3.yml@v1.9.0
    with:
      image: ${{ inputs.image }}
      digest: ${{ inputs.digest }}
    secrets: 
      registry-username: ${{ secrets.DOCKER_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
